spring:
  profiles:
    include: route
  application:
    name: gateway
  cloud:
    nacos:
      server-addr: ${NACOS_SERVER_ADDR:127.0.0.1:8848}
      username: ${NACOS_USERNAME:nacos}
      password: ${NACOS_PASSWORD:nacos}
      discovery:
        namespace: ${NACOS_NAMESPACE:public}
        group: DEFAULT_GROUP
        username: ${NACOS_USERNAME:nacos}
        password: ${NACOS_PASSWORD:nacos}
      config:
        namespace: ${NACOS_NAMESPACE:public}
        username: ${NACOS_USERNAME:nacos}
        password: ${NACOS_PASSWORD:nacos}
    loadbalancer:
      nacos:
        enabled: true
#    sentinel:
#      transport:
#        dashboard: ${SENTINEL_DASHBOARD:localhost:8858}
#        port: 8720
#      eager: true
#      datasource:
#        gw-flow:
#          nacos:
#            server-addr: ${NACOS_SERVER_ADDR:127.0.0.1:8848}
#            namespace: ${NACOS_NAMESPACE:public}
#            username: ${spring.cloud.nacos.username}
#            password: ${spring.cloud.nacos.password}
#            dataId: gateway-flow-rules
#            groupId: SENTINEL_GROUP
#            data-type: json
#            rule-type: gw-flow
#        gw-api-group:
#          nacos:
#            server-addr: ${NACOS_SERVER_ADDR:127.0.0.1:8848}
#            namespace: ${NACOS_NAMESPACE:public}
#            username: ${spring.cloud.nacos.username}
#            password: ${spring.cloud.nacos.password}
#            dataId: gateway-api-group-rules
#            groupId: SENTINEL_GROUP
#            data-type: json
#            rule-type: gw-api-group

server:
  port: ${GATEWAY_SERVER_PORT:9090}

demo:
  tracing:
    enabled: ${DEMO_TRACING_ENABLED:false}

logging:
  charset:
    console: UTF-8
  level:
    com.alibaba.cloud.nacos: DEBUG
    org.springframework.cloud.gateway: DEBUG
    org.springframework.cloud.loadbalancer: DEBUG

management:
  endpoint:
    health:
      probes:
        enabled: true
  endpoints:
    web:
      exposure:
        include: "*"

---
#spring:
#  config:
#    import:
#      - nacos:gateway-common.yaml?group=gateway
#    activate:
#      on-profile: dev

---
#spring:
#  config:
#    import:
#      - nacos:gateway-common.yaml?group=gateway
#    activate:
#      on-profile: test

---
#spring:
#  config:
#    import:
#      - nacos:gateway-common.yaml?group=gateway
#    activate:
#      on-profile: prod



