spring:
  application:
    name: seata-storage
  config:
    import:
      - optional:nacos:common.yaml?group=SEATA_GROUP
  datasource:
    url: jdbc:mysql://localhost:3306/storage_db?useUnicode=true&characterEncoding=utf-8&useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=Asia/Shanghai
    username: root
    password: MyP@ssw0rd123!
    driver-class-name: com.mysql.cj.jdbc.Driver
  cloud:
    nacos:
      server-addr: 172.29.64.1:8848
      username: nacos
      password: nacos
      discovery:
        namespace: 8699ba10-d5ae-4183-aa94-eef36789f4d3
      config:
        namespace: 8699ba10-d5ae-4183-aa94-eef36789f4d3
server:
  port: 23000

mybatis:
  mapper-locations: classpath:mapper/*.xml
seata:
  application-id: seata-storage
