spring:
  application:
    name: seata-business
  cloud: 
    nacos: 
      server-addr: 172.29.64.1:8848
      username: nacos 
      password: nacos
      discovery:
        namespace: 8699ba10-d5ae-4183-aa94-eef36789f4d3
      config:
        namespace: 8699ba10-d5ae-4183-aa94-eef36789f4d3
  config:
    import:
      - optional:nacos:common.yaml?group=SEATA_GROUP
  
server:
  port: 21000
seata:
  application-id: seata-business
