spring:
  application:
    name: seata-business
  cloud: 
    nacos: 
      server-addr: ${NACOS_SERVER_ADDR:127.0.0.1:8848}
      username: ${NACOS_USERNAME:nacos} 
      password: ${NACOS_PASSWORD:nacos}
      discovery:
        namespace: ${NACOS_NAMESPACE:public}
      config:
        namespace: ${NACOS_NAMESPACE:public}
  config:
    import:
      - optional:nacos:common.yaml?group=SEATA_GROUP
  
server:
  port: 21000
seata:
  application-id: seata-business

